#!/usr/bin/env php
<?php

	function startProcess($cmd) {
		$descriptorspec = [
			0 => STDIN,
			1 => STDOUT,
			2 => STDERR,
		];

		return proc_open($cmd, $descriptorspec, $pipes);
	}

	function stopProcess($proc) {
		if (is_resource($proc)) {
			proc_terminate($proc);
			proc_close($proc);
		}
	}

	echo "Starting PHP server and NPM watcher...\n";
	echo "Type 'exit' and press Enter to stop.\n\n";

	$phpProc = startProcess('php -S localhost:8000 -t public');
	$npmProc = startProcess('npm run watch');

	while (true) {
		$input = trim(fgets(STDIN));

		if ($input === 'exit') {
			echo "Stopping processes...\n";
			stopProcess($phpProc);
			stopProcess($npmProc);
			break;
		}
	}